# Generated by Django 5.0 on 2024-04-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=64)),
                ("email", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=32)),
                ("phone", models.CharField(max_length=32)),
                ("academy", models.IntegerField()),
                ("avatar", models.CharField(max_length=200)),
            ],
        ),
    ]
