# Generated by Django 5.0 on 2024-04-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "00010_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=64)),
                ("email", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=32)),
                ("avatar", models.CharField(max_length=200)),
                ("is_super_admin", models.BooleanField()),
            ],
        ),
    ]
