# Generated by Django 4.1.3 on 2024-04-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_alter_admin_table_alter_student_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_id", models.IntegerField(max_length=32)),
                ("reason", models.CharField(max_length=64)),
                ("time_slot", models.TimeField()),
                ("read", models.BooleanField()),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.admin"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.student"
                    ),
                ),
            ],
            options={
                "db_table": "Notification",
            },
        ),
    ]
