# Generated by Django 5.0 on 2024-04-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_alter_notification_notification_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "Picture",
            },
        ),
        migrations.CreateModel(
            name="Push",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("push_id", models.IntegerField()),
                ("title", models.CharField(max_length=64)),
                ("pre_content", models.CharField(max_length=64)),
                ("picture", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "Push",
            },
        ),
        migrations.AlterField(
            model_name="student",
            name="academy",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="avatar",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
