# Generated by Django 5.0 on 2024-04-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_picture_push_alter_student_academy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="is_super_admin",
        ),
    ]
