# Generated by Django 4.1.3 on 2024-05-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0016_remove_admin_is_super_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="academy",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="phone",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="admin",
            name="avatar",
            field=models.FileField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="admin",
            name="name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="avatar",
            field=models.FileField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
