# Generated by Django 5.0 on 2024-04-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_remove_admin_is_super_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="academy",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="avatar",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
