# Generated by Django 4.2.11 on 2024-05-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_admin_academy_admin_phone_alter_admin_avatar_and_more'),
    ]

    operations = [
    ]
