# Generated by Django 4.2.11 on 2024-05-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_admin_academy'),
    ]

    operations = [
    ]
