# Generated by Django 5.0 on 2024-05-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_alter_admin_avatar_alter_student_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="avatar",
            field=models.FileField(
                blank=True,
                default="media/default_avatar",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
