# Generated by Django 4.1.3 on 2024-05-26 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0019_admin_phone"),
        ("base", "0019_alter_admin_avatar"),
    ]

    operations = []
