# Generated by Django 4.1.3 on 2024-05-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0020_merge_0019_admin_phone_0019_alter_admin_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="push",
            name="address",
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name="notification",
            name="time_slot",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="picture",
            name="image",
            field=models.FileField(upload_to="pictures/"),
        ),
        migrations.AlterField(
            model_name="push",
            name="picture",
            field=models.FileField(upload_to="pushes/"),
        ),
        migrations.AlterField(
            model_name="student",
            name="academy",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
