# Generated by Django 4.1.3 on 2024-06-10 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0021_push_address_alter_notification_time_slot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=64)),
                ("code", models.CharField(max_length=256)),
                ("type", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "EmailVerify",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="notification",
            name="admin",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.admin"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="read",
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name="notification",
            name="reason",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
