# Generated by Django 4.1.3 on 2024-05-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=1000)),
                ("answer", models.CharField(max_length=1000)),
            ],
            options={
                "db_table": "Problem",
            },
        ),
    ]
