# Generated by Django 4.1.3 on 2024-04-26 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_remove_order_admin_remove_order_order_person_role_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="order",
            table="Order",
        ),
        migrations.AlterModelTable(
            name="place",
            table="Place",
        ),
        migrations.AlterModelTable(
            name="team",
            table="Team",
        ),
        migrations.AlterModelTable(
            name="teammember",
            table="TeamMember",
        ),
    ]
