# Generated by Django 4.1.3 on 2024-04-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_alter_place_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="capacity",
            field=models.IntegerField(default=20),
        ),
    ]
