# Generated by Django 4.2.11 on 2024-05-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_team_alter_place_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='capacity',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
