# Generated by Django 4.2.11 on 2024-05-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_team_alter_place_status'),
        ('order', '0007_alter_place_capacity_alter_place_status'),
    ]

    operations = [
    ]
