# Generated by Django 4.1.3 on 2024-06-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0008_merge_20240503_0737"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
