# Generated by Django 4.1.3 on 2024-04-26 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="lecturer",
            table="Lecturer",
        ),
    ]
