# Generated by Django 5.0 on 2024-04-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_lectureplace"),
        ("order", "0004_alter_place_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LecturePlace",
            new_name="LecturerPlace",
        ),
    ]
