# Generated by Django 4.1.3 on 2024-04-28 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0004_rename_lectureplace_lecturerplace"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lecturerplace",
            old_name="lecture",
            new_name="lecturer",
        ),
    ]
